services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: observekit
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: secret
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: observekit
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret

volumes:
  clickhouse_data:
  redis_data:
  postgres_data: